export const HERO_SCROLL_STAGE_CONFIG = {
  mobile: {
    subtitleVisualDrop: 56,
    socialVisualDrop: 104,
    subtitleSplitX: -56,
    socialSplitX: 56,
    subtitleSplitY: 52,
    socialSplitY: 72,
    socialPreSplitDrop: 18,
    subtitleLateDrop: 26,
    socialCornerLift: -18,
    subtitleAboveSocialGap: -18,
    preFadeDropBoth: 18,
    subtitleFinalDip: 20,
    subtitlePreReturnDrop: 18,
    socialPreBlurDrop: 34,
    socialReturnDrop: 18,
  },
  desktop: {
    subtitleVisualDrop: 82,
    socialVisualDrop: 168,
    subtitleSplitX: -185,
    socialSplitX: 225,
    subtitleSplitY: 60,
    socialSplitY: 126,
    socialPreSplitDrop: 20,
    subtitleLateDrop: 32,
    socialCornerLift: -20,
    subtitleAboveSocialGap: -20,
    preFadeDropBoth: 20,
    subtitleFinalDip: 24,
    subtitlePreReturnDrop: 20,
    socialPreBlurDrop: 40,
    socialReturnDrop: 20,
  },
};
